// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillMatch.API.Models;

#nullable disable

namespace SkillMatch.API.Migrations
{
    [DbContext(typeof(SkillMatchDbContext))]
    partial class SkillMatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SkillMatch.API.Models.Application", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<ulong>("JobId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'APPLIED'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CandidateId" }, "candidate_id");

                    b.HasIndex(new[] { "JobId", "CandidateId" }, "uq_job_candidate")
                        .IsUnique();

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.AuditLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.CandidateProfile", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("education_level");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("headline");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<decimal?>("TotalExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_experience_years")
                        .HasDefaultValueSql("'0.0'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique()
                        .HasDatabaseName("user_id1");

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.CandidateSkill", b =>
                {
                    b.Property<ulong>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<ulong>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<bool?>("IsVerifiedByUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_verified_by_user")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal?>("YearsExperience")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("years_experience")
                        .HasDefaultValueSql("'0.0'");

                    b.HasKey("CandidateId", "SkillId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SkillId" }, "skill_id");

                    b.ToTable("candidate_skills", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("JobType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("job_type")
                        .HasDefaultValueSql("'FULL_TIME'");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<decimal?>("MaxExperienceYears")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_experience_years");

                    b.Property<decimal?>("MinExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("min_experience_years")
                        .HasDefaultValueSql("'0.0'");

                    b.Property<ulong>("RecruiterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "category_id");

                    b.HasIndex(new[] { "Status" }, "idx_job_status");

                    b.HasIndex(new[] { "RecruiterId" }, "recruiter_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobCategory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("job_categories", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobSkill", b =>
                {
                    b.Property<ulong>("JobId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_id");

                    b.Property<ulong>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<bool?>("IsMandatory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_mandatory")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("JobId", "SkillId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SkillId" }, "skill_id")
                        .HasDatabaseName("skill_id1");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.MatchResult", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ulong>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("computed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("ExperienceFitScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("experience_fit_score");

                    b.Property<string>("ExplanationNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("explanation_notes");

                    b.Property<ulong>("JobId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_id");

                    b.Property<string>("MatchedSkillsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched_skills_json");

                    b.Property<string>("MissingSkillsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("missing_skills_json");

                    b.Property<decimal>("OverallMatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("overall_match_score");

                    b.Property<decimal>("SemanticFitScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("semantic_fit_score");

                    b.Property<decimal>("SkillMatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("skill_match_score");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OverallMatchScore" }, "idx_overall_score");

                    b.HasIndex(new[] { "JobId" }, "job_id");

                    b.HasIndex(new[] { "CandidateId", "JobId" }, "uq_match_candidate_job")
                        .IsUnique();

                    b.ToTable("match_results", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.RecruiterProfile", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_size");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_website");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("designation");

                    b.Property<bool?>("IsApprovedByAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_approved_by_admin")
                        .HasDefaultValueSql("'0'");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique()
                        .HasDatabaseName("user_id2");

                    b.ToTable("recruiter_profiles", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ulong>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<uint>("FileSizeKb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_kb");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<string>("ParsedRawText")
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_raw_text");

                    b.Property<string>("ParsingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("parsing_status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CandidateId" }, "idx_resume_candidate");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.Skill", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category")
                        .HasDefaultValueSql("'Technical'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "idx_skill_name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'CANDIDATE'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Role" }, "idx_user_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SkillMatch.API.Models.Application", b =>
                {
                    b.HasOne("SkillMatch.API.Models.CandidateProfile", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_ibfk_2");

                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_ibfk_1");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillMatch.API.Models.AuditLog", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("audit_logs_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.CandidateProfile", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("SkillMatch.API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_profiles_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.CandidateProfile", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_skills_ibfk_1");

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_skills_ibfk_2");

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.HasOne("SkillMatch.API.Models.JobCategory", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("jobs_ibfk_2");

                    b.HasOne("SkillMatch.API.Models.RecruiterProfile", "Recruiter")
                        .WithMany("Jobs")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("jobs_ibfk_1");

                    b.Navigation("Category");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_skills_ibfk_1");

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_skills_ibfk_2");

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.MatchResult", b =>
                {
                    b.HasOne("SkillMatch.API.Models.CandidateProfile", "Candidate")
                        .WithMany("MatchResults")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("match_results_ibfk_1");

                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("MatchResults")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("match_results_ibfk_2");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillMatch.API.Models.RecruiterProfile", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithOne("RecruiterProfile")
                        .HasForeignKey("SkillMatch.API.Models.RecruiterProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recruiter_profiles_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.HasOne("SkillMatch.API.Models.CandidateProfile", "Candidate")
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resumes_ibfk_1");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SkillMatch.API.Models.CandidateProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateSkills");

                    b.Navigation("MatchResults");

                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");

                    b.Navigation("MatchResults");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SkillMatch.API.Models.RecruiterProfile", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CandidateProfile");

                    b.Navigation("RecruiterProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
